version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "rinha"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=50' -c 'fsync=off' -c 'synchronous_commit=off' -c 'checkpoint_timeout=1d' -c 'full_page_writes=false'
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: 200MB
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    network_mode: host
    depends_on:
      - db
